SQLALCHEMY_DATABASE_URL: "postgresql://postgres:postgres546825@192.168.0.3:5432/test"
SECRET_KEY: "8cfba7f89fca29a5f86cd8e02cb5381070690e378fc26cce4a311f84ce93673a"
ALGORITHM: "HS256"
TOKEN_URL: "login"
TOKEN_EXPIRATION_TIME: 15
ALLOW_SELF_REGISTRATION: False
ALLOW_CREDENTIALS: False
ALLOWED_ORIGINS:
  - "*"
ALLOWED_METHODS:
  - "*"
ALLOWED_HEADERS:
  - "*"