[project]
name = "FasterAPI"
version = "0.0.22"
authors = [
  { name="Yifei Ren", email="ryf0510@live.com" },
]
description = "Just a FasterAPI starting point with JWT user authentication."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "fastapi[all]",
  "sqlalchemy",
  "colorlog",
  "python-jose[cryptography]",
  "bcrypt==4.0.1",
  "passlib[bcrypt]",
  "psycopg2-binary",
]

[project.urls]
"Homepage" = "https://github.com/ulfaric/FasterAPI"
"Bug Tracker" = "https://github.com/ulfaric/FasterAPI/issues"

[tool.setuptools]
packages = ["FasterAPI"]